# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vdKpeB_nj5vsyGq_OW1yJlxA9oMmjFYu
"""

import streamlit as st

def largest_num(a, b, c):
  return max(list((a,b,c)))

st.title("Find the largest among 3 numbers")
st.write("Enter three numbers below:")

num1 = st.number_input("Number 1")
num2 = st.number_input("Number 2")
num3 = st.number_input("Number 3")

if st.button("Find largest number"):
    largest = largest_num(num1, num2, num3)
    st.write(f"The largest number is {largest}")